# Site settings
author: Nicholas Wilson
title: My Flatiron Bootcamp Journey
header-img: img/home-bg.png
email: nicholas.wilson@nevada.unr.edu
copyright_name: Nicholas Wilson
description: > # this means to ignore newlines until "baseurl:"
  Learning how to Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nicholas-wilson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
